src/Entity/Grade.php
<?php

namespace App\Entity;

use App\Repository\GradeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=GradeRepository::class)
 */
class Grade
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $lecture_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $student_id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="Grade should be a positive integer.")
     */
    private $grade;

    /**
     * @ORM\ManyToOne(targetEntity=Lecture::class, inversedBy="grades")
     */
    private $lecture;

    /**
     * @ORM\ManyToOne(targetEntity=Student::class, inversedBy="grades")
     */
    private $student;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLectureId(): ?int
    {
        return $this->lecture_id;
    }

    public function setLectureId(int $lecture_id): self
    {
        $this->lecture_id = $lecture_id;

        return $this;
    }

    public function getStudentId(): ?int
    {
        return $this->student_id;
    }

    public function setStudentId(int $student_id): self
    {
        $this->student_id = $student_id;

        return $this;
    }

    public function getGrade(): ?int
    {
        return $this->grade;
    }

    public function setGrade(int $grade): self
    {
        $this->grade = $grade;

        return $this;
    }

    public function getLecture(): ?Lecture
    {
        return $this->lecture;
    }

    public function setLecture(?Lecture $lecture): self
    {
        $this->lecture = $lecture;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): self
    {
        $this->student = $student;

        return $this;
    }
}

src/Controller/GradeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Lecture;
use App\Entity\Student;
use App\Entity\Grade;

class GradeController extends AbstractController
{
    /**
     * @Route("/grade", name="grade_index")
     */
    public function index(request $r): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        
        $lectures = $this->getDoctrine()
            ->getRepository(Lecture::class)
            ->findBy([],['name'=>'asc']);

        $students = $this->getDoctrine()
            ->getRepository(Student::class)
            ->findBy([],['surname'=>'asc']);

        $grades = $this->getDoctrine()
            ->getRepository(Grade::class);
            if ($r->query->get('student_id') !== null && $r->query->get('student_id') != 0) 
                $grades = $grades->findBy(['student_id' => $r->query->get('student_id')]);
            elseif ($r->query->get('student_id') == 0) $grades = $grades->findAll();
            else $grades = $grades->findAll();

        return $this->render('grade/index.html.twig', [
            'controller_name' => 'GradeController',
            'studentId' => $r->query->get('student_id') ?? 0,
            'grades' => $grades,
            'lectures' => $lectures,
            'students' => $students,
            'success' => $r->getSession()->getFlashBag()->get('success', [])
        ]);
    }

    /**
     * @Route("/grade/create", name="grade_create", methods={"GET"})
     */
    public function create(request $r): Response
    {
        $lectures = $this->getDoctrine()
            ->getRepository(Lecture::class)
            ->findBy([],['name'=>'asc']);

        $students = $this->getDoctrine()
            ->getRepository(Student::class)
            ->findBy([],['surname'=>'asc']);

        $grade_grade = $r->getSession()->getFlashBag()->get('grade_grade', []);

        return $this->render('grade/create.html.twig', [
            'lectures' => $lectures,
            'students' => $students,
            'grade_grade' => $grade_grade[0] ?? '',
            'grade_student_id' => $grade_student_id[0] ?? '',
            'grade_lecture_id' => $grade_grade_id[0] ?? '',
            'errors' => $r->getSession()->getFlashBag()->get('errors', [])
        ]);
    }

    /**
     * @Route("/grade/store", name="grade_store", methods={"POST"})
     */
    public function store(request $r, ValidatorInterface $validator): Response
    {
        $student = $this->getDoctrine()
            ->getRepository(Student::class)
            ->find($r->request->get('grades_student'));

        $lecture = $this->getDoctrine()
            ->getRepository(Lecture::class)
            ->find($r->request->get('grades_lecture'));

        if($student == null) $r->getSession()->getFlashBag()->add('errors', 'Student must be selected.');
        if($lecture == null) $r->getSession()->getFlashBag()->add('errors', 'Lecture must be selected.');

        $grade = new Grade;
        $grade
            ->setGrade((int)$r->request->get('grade_grade'))
            ->setStudent($student)
            ->setLecture($lecture);

        $errors = $validator->validate($grade);
        if (count($errors) > 0 or $lecture == null or $student == null) {
            foreach ($errors as $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }
            $r->getSession()->getFlashBag()->add('grade_grade', $r->request->get('grade_grade'));
            $r->getSession()->getFlashBag()->add('grade_student_id', $r->request->get('grade_student_id'));
            $r->getSession()->getFlashBag()->add('grade_lecture_id', $r->request->get('grade_lecture_id'));

            return $this->redirectToRoute('grade_create');
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($grade);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Grade '.$grade->getGrade().' from '.$grade->getLecture()->getName().' for '.$grade->getStudent()->getName().' '.$grade->getStudent()->getSurname().' was created.');

        return $this->redirectToRoute('grade_index');
    }

    /**
     * @Route("/grade/edit/{id}", name="grade_edit", methods={"GET"})
     */
    public function edit(int $id, request $r): Response
    {
        $grade = $this->getDoctrine()
            ->getRepository(Grade::class)
            ->find($id);

        $lectures = $this->getDoctrine()
            ->getRepository(Lecture::class)
            ->findBy([],['name'=>'asc']);

        $students = $this->getDoctrine()
            ->getRepository(Student::class)
            ->findBy([],['surname'=>'asc']);

        return $this->render('grade/edit.html.twig', [
            'grade' => $grade,
            'lectures' => $lectures,
            'students' => $students,
            'errors' => $r->getSession()->getFlashBag()->get('errors', []),
            'success' => $r->getSession()->getFlashBag()->get('success', [])
        ]);
    }

    /**
     * @Route("/grade/update/{id}", name="grade_update", methods={"POST"})
     */
    public function update(request $r, $id, ValidatorInterface $validator): Response
    {
        $student = $this->getDoctrine()
            ->getRepository(Student::class)
            ->find($r->request->get('grades_student'));

        $lecture = $this->getDoctrine()
            ->getRepository(Lecture::class)
            ->find($r->request->get('grades_lecture'));

        $grade = $this->getDoctrine()
            ->getRepository(Grade::class)
            ->find($id);
        
        $grade
            ->setGrade($r->request->get('grade_grade'))
            ->setStudent($student)
            ->setLecture($lecture);

        $errors = $validator->validate($grade);
        if (count($errors) > 0) {
            foreach ($errors as $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }
            return $this->redirectToRoute('grade_edit', ['id'=>$grade->getId()]);
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($grade);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Grade '.$grade->getGrade().' from '.$grade->getLecture()->getName().' for '.$grade->getStudent()->getName().' '.$grade->getStudent()->getSurname().' was updated.');

        return $this->redirectToRoute('grade_index');
    }

    /**
     * @Route("/grade/delete/{id}", name="grade_delete", methods={"POST"})
     */
    public function delete(request $r, int $id): Response
    {
        $grade = $this->getDoctrine()
            ->getRepository(Grade::class)
            ->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($grade);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Grade '.$grade->getGrade().' from '.$grade->getLecture()->getName().' for '.$grade->getStudent()->getName().' '.$grade->getStudent()->getSurname().' was deleted.');

        return $this->redirectToRoute('grade_index');
    }

}

templates/grade/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create new Grade{% endblock %}

{% block body %}
<div class="container">
<div class="row bg">
    <h1 class="create">Create new Grade</h1>
    <div class="container create col-sm-4">
        <form action="{{path('grade_store')}}" method="POST">
            <div class="new">
                <label for="grades_student">Student:</label>
                <select name="grades_student" id="grades_student">
                    <option value="0">Select student</option>
                    {% for student in students %}
                        <option value="{{student.id}}">{{student.name}} {{student.surname}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="new">
                <label for="grades_lecture">Lecture:</label>
                <select name="grades_lecture" id="grades_lecture">
                    <option value="0">Select lecture</option>
                    {% for lecture in lectures %}
                        <option value="{{lecture.id}}">{{lecture.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="new">
                <label for="grade_grade">Grade:</label>
                <input type="text" name="grade_grade" id="grade_grade">
            </div>
            <button class="submit-btn create" type="submit">Add new Grade</button>
            {# <input type="hidden" name="token" value="{{csrf_token('')}}"/> #}
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/grade/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create new Grade{% endblock %}

{% block body %}
<div class="container">
<div class="row bg">
    <h1 class="create">Edit Grade</h1>
    <div class="container create col-sm-4">
        <form action="{{path('grade_update', {id: grade.id})}}" method="POST">
            <div class="new">
                <label for="grades_student">Student:</label>
                <select name="grades_student" id="grades_student">
                    {% for student in students %}
                        <option value="{{student.id}}"{% if student.id == grade.studentId %} selected {% endif %}>{{student.name}} {{student.surname}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="new">
                <label for="grades_lecture">Lecture:</label>
                <select name="grades_lecture" id="grades_lecture">
                    {% for lecture in lectures %}
                        <option value="{{lecture.id}}"{% if lecture.id == grade.lectureId %} selected {% endif %}>{{lecture.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="new">
                <label for="grade_grade">Grade:</label>
                <input type="text" name="grade_grade" value="{{grade.grade}}" id="grade_grade">
            </div>
            <button class="submit-btn create" type="submit">Edit Grade</button>
            {# <input type="hidden" name="token" value="{{csrf_token('')}}"/> #}
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/grade/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Grades{% endblock %}

{% block body %}
<div class="container">
    <div class="row bg">
        <h1>Grades</h1>
        <div class="filter">
            <p>Filter list by:</p>
            <form action="{{path('grade_index')}}" method="GET">
                <select name="student_id">
                    <option value="0">View all</option>
                    {% for student in students %}
                        <option value="{{student.id}}" {% if studentId == student.id %} selected {% endif %}>{{student.name}} {{student.surname}}</option>
                    {% endfor %}
                </select>
                <button class="filter submit-btn" type="submit">Filter</button>
            </form>
            <a href="{{path('grade_index')}}">Clear filter</a>
        </div>
        <div class="container item-list">
            <ul class="row">
                {% if grades is empty %}
                <p>There are no grades to show for selected student.</p>
                {% endif %}
                {% for grade in grades %}
                <div class="col-sm-4">
                    <div class="pic"><div class="preview item"></div></div>
                    <p class="name">
                        {{grade.student.name}} {{grade.student.surname}} 
                    </p>
                    <p class="name">{{grade.lecture.name}}</p>
                    <p class="title">Grade: {{grade.grade}}</p>
                    <div class="buttons wide">
                        <a class="edit-btn" href="{{path('grade_edit', {id: grade.id})}}">Edit</a>
                        <form action="{{path('grade_delete', {id:grade.id})}}" method="POST">
                            <button class="submit-btn" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}